name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.x
        check-latest: true

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Release Notes
      run: ./resources/scripts/release_notes.sh > ./release_notes.md

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --release-notes=./release_notes.md --timeout 60m
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}